version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/angular"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/node"
    schedule:
      interval: "weekly"

